// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'contentLink': string;
  'links': string;
  'modernScriptEditor': string;
  'teams': string;
  'title': string;
  'welcome': string;
  'welcomeImage': string;
}
const cssExports: CssExports;
export default cssExports;
